# Generated by Django 5.2 on 2025-04-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='stores',
            field=models.ManyToManyField(to='books.store', verbose_name='магазины'),
        ),
    ]
